name: Merge AtCoder Problems

on:
  push:
    branches:    
      - master

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run
      run: |
        npm install
        npm install ts-node -g
        npm run tree:parse
        mkdir dist
        npm run merge > dist/run.log
        cp data/result.json dist/result.json
        cp data/invalid_lines dist/invalid_lines.txt
        cp data/readme.md dist/readme.md
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist